name: Password Validation Workflow

on:
  push:
    branches:
      - main

jobs:
  validate_password:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variable
        env:
          PASSWORD: ${{ secrets.SECRET_NAME1 }}
        run: |
          echo "Please enter the password:"
          read USER_INPUT

          if [ "$USER_INPUT" == "$PASSWORD" ]; then
            echo "Success: The password is correct."
          else
            echo "Failed: The password is incorrect."
            exit 1
          fi
